dependency update to support flutter 3.22.0 +
flutter-form-builder-ecosystem/form_builder_phone_field pull request #63
Opened 2024-06-13 08:57 UTC by nicks258

## Connection with issue(s)

Close #[62](https://github.com/flutter-form-builder-ecosystem/form_builder_phone_field/issues/62)

Connected Flutter 3.22.0 +

## Solution description
Updated child dependency

- phone_number: ^2.1.0
- flutter_lints: ^4.0.0
- dart sdk: ">=3.3.0 <4.0.0"

2024-06-13 10:27 UTC, deandreamatias requested changes

2024-06-13 10:27 UTC, deandreamatias commented on example/pubspec.yaml
> -  flutter: ">=3.10.0"
Please add this line 

```dart
flutter: ">=3.22.0"
```

2024-06-13 10:44 UTC, nicks258 commented on example/pubspec.yaml
> -  flutter: ">=3.10.0"
Done with adding flutter constrain.

2024-06-13 11:11 UTC, deandreamatias approved these changes

2024-06-13 11:12 UTC, deandreamatias commented
Now will be required that pass pipeline and I will merge it

2024-06-14 12:20 UTC, dthuesen commented
Since its only a matter of the small analyzer issue in the pipeline "Convert 'key' to a super parameter • example/lib/main.dart:12:9 • use_super_parameters", how long do you think it will take to fix it?

2024-06-19 05:45 UTC, nicks258 commented
Hi @deandreamatias I have push the commit to solve analyzer issue. Can you merge it now. Thanks.

2024-06-20 05:37 UTC, nicks258 commented
@deandreamatias updated PhoneNumberKit tag to 3.6.0 to solve pod issue. I Hope this will be merge now (;

2024-06-20 13:52 UTC, merged